package service.httpServer;

public enum Endpoint {
    GET_TASKS,
    GET_TASK_BY_ID,
    POST_UPDATE_TASK,
    POST_ADD_TASK,
    DELETE_TASKS,
    DELETE_TASK_BY_ID,

    GET_EPICS,
    GET_EPIC_BY_ID,
    POST_UPDATE_EPIC,
    POST_ADD_EPIC,
    DELETE_EPIC,
    DELETE_EPIC_BY_ID,

    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    POST_UPDATE_SUBTASK,
    POST_ADD_SUBTASK,
    DELETE_SUBTASKS,
    DELETE_SUBTASK_BY_ID,

    GET_EPIC_BY_SUBTASK_ID,
    GET_HISTORY,
    GET_PRIOR_TASKS,

    UNKNOWN
}
